---
swagger: "2.0"
info:
  description: "API para acompanhamento de pedidos.\n[http://swagger.io](http://swagger.io)\
    \ or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: "1.0.0"
  title: "Order Tracking"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "anjovisk@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/anjovisk/order-tracker/1.0.0"
tags:
- name: "order-tracking"
  description: "Informações de rastreamento dos pedidos."
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
paths:
  /trackings:
    get:
      tags:
      - "trackings"
      summary: "Obtém o rastreamento de um pedido"
      description: "Lista as movimentações de um pedido de acordo com o código de\
        \ rastreamento"
      operationId: "findByTrackingNumber"
      produces:
      - "application/json"
      parameters:
      - name: "trackingNumber"
        in: "query"
        description: "Código de rastreamento para obter as movimentações"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tracking"
        "404":
          description: "Encomenda não encontrada"
      x-swagger-router-controller: "Trackings"
  /orders:
    post:
      tags:
      - "orders"
      summary: "Adiciona um novo pedido para rastreamento."
      operationId: "addOrder"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - in: "body"
        name: "body"
        description: "Pedido que será rastreado."
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "Orders"
  /orders/{orderId}:
    get:
      tags:
      - "orders"
      summary: "Obtém um pedido pelo id"
      description: "Retorna um único pedido"
      operationId: "getOrderById"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "orderId"
        in: "path"
        description: "Id do pedido"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        "404":
          description: "Order not found"
      x-swagger-router-controller: "Orders"
    put:
      tags:
      - "orders"
      summary: "Atualiza as informações de um pedido."
      operationId: "updateOrder"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "orderId"
        in: "path"
        description: "Id do pedido"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Pedido que será rastreado."
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Order"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
        "405":
          description: "Validation exception"
      x-swagger-router-controller: "Orders"
    delete:
      tags:
      - "orders"
      summary: "Remove um pedido"
      operationId: "deleteOrder"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "orderId"
        in: "path"
        description: "Id do pedido que será excluído"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pedido não encontrado"
      x-swagger-router-controller: "Orders"
  /orders/{orderId}/trackings:
    get:
      tags:
      - "trackings"
      summary: "Obtém as movimentações de um pedido"
      description: "Retorna uma lista de movimentações"
      operationId: "getTrackings"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "orderId"
        in: "path"
        description: "Id do pedido"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Tracking"
        "404":
          description: "Order not found"
      x-swagger-router-controller: "Trackings"
    post:
      tags:
      - "trackings"
      summary: "Adiciona uma movimentação"
      operationId: "addTracking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "orderId"
        in: "path"
        description: "Id do pedido"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Pedido que será rastreado."
        required: true
        schema:
          $ref: "#/definitions/Tracking"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Tracking"
      x-swagger-router-controller: "Trackings"
definitions:
  Tracking:
    type: "object"
    required:
    - "date"
    - "movement"
    properties:
      details:
        type: "string"
        description: "Detalhes da movimentação, de/para, etc."
      date:
        type: "string"
        format: "date-time"
      movement:
        type: "string"
        description: "Tipo de movimentação"
        enum:
        - "POSTED"
        - "MOVEMENT"
        - "OUT_FOR_DELIVERY"
        - "DELIVERY_FAILED"
        - "DELIVERED"
        - "RETURNED"
    example:
      date: "2000-01-23T04:56:07.000+00:00"
      details: "details"
      movement: "POSTED"
  Order:
    type: "object"
    required:
    - "orderNumber"
    properties:
      _id:
        type: "string"
        description: "Identificador único do pedido"
      orderNumber:
        type: "string"
        description: "Número do pedido"
      trackingNumber:
        type: "string"
        description: "Número de rastreamento"
      registrationDate:
        type: "string"
        format: "date-time"
      lastUpdate:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        description: "Order Status"
        enum:
        - "POSTED"
        - "ON_ROUTE"
        - "OUT_FOR_DELIVERY"
        - "DELIVERY_FAILED"
        - "DELIVERED"
        - "RETURNING"
        - "RETURNED"
    xml:
      name: "Order"
    example:
      orderNumber: "orderNumber"
      lastUpdate: "2000-01-23T04:56:07.000+00:00"
      _id: "_id"
      registrationDate: "2000-01-23T04:56:07.000+00:00"
      trackingNumber: "trackingNumber"
      status: "POSTED"
  Recipient:
    type: "object"
    required:
    - "address"
    - "name"
    properties:
      name:
        type: "string"
        description: "Nome do destinatário"
      document:
        type: "string"
        description: "RG do destinatário"
      address:
        $ref: "#/definitions/Address"
    xml:
      name: "Recipient"
  Address:
    type: "object"
    required:
    - "city"
    - "number"
    - "postalCode"
    - "state"
    - "street"
    properties:
      postalCode:
        type: "string"
        description: "Código postal (CEP)"
      street:
        type: "string"
        description: "Logradouro"
      number:
        type: "string"
        description: "Número"
      complement:
        type: "string"
        description: "Complemento"
      city:
        type: "string"
        description: "Cidade"
      state:
        type: "string"
        description: "Estado"
    xml:
      name: "Address"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
